sudo: false

language: php

php:
  - 7.0
  - 7.1
  - hhvm

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer update $DEPENDENCIES

script:
  - ./vendor/bin/phpunit

notifications:
  irc: "irc.freenode.org#zftalk.modules"
