language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests

after_script:
  - php vendor/bin/coveralls -v

notifications:
  irc: "irc.freenode.org#zftalk.modules"
